config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'

  devise_for :users

  resources :products do
    resources :reviews
  end

  resources :categories

  resources :cart_line_items

  resources :orders

  get '/site/hello'
  get '/site/goodbye'
  get '/site/categories'
  get '/site/products'

  resources :articles

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
		if params[:sort].nil?
			@products = @category.products
		elsif params[:sort] == "low-high"
			@products = @category.products.order('price')
		elsif params[:sort] == "high-low"
			@products = @category.products.order('price DESC')
		end
				
			
	end
		

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<H2> Listing Categories( <%= @categories.count%> ) </H2>

<% if @categories.empty? %>
 <p> Categories not added yet</p>

<% else %>


<ul>
		<% @categories.each do |category| %>
			<li> <%= link_to category.name, category_path(category)%> 
			<%#= product.get_category_name : This uses a method that we created in the Class%> 
			<%#= product.category.name : This uses associations but if a foreign key is null it will throw an error for nil::NilClass, which can be handled using try%>
			<!--  #here we can call the method like we have done in the show page. Show page is the preferred way to do it -->
				

			</li>



		<%end%>

	</ul>

<% end %>

app/views/categories/show.html.erb
<H2> <%= @category.name %>  </H2> 

<p> Total Products = <%= @category.products.size %></p>
 
<H2> Listing Products</H2>
<p>Sort : Price <%= link_to "low-high", category_path(@category, sort: "low-high")%> | <%= link_to "high-low", category_path(@category, sort: "high-low")%> </p>

<ul>
 <%@products.each do |product|%>
 	<li> <%= link_to product.name, product_path(product)%> <%= product.price%></li>
 	<% end %>

</ul>

<%= link_to("Back",categories_path)%>