config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'

  devise_for :users

  resources :products do
    resources :reviews
  end

  resources :categories

  resources :cart_line_items

  resources :orders

  get '/site/hello'
  get '/site/goodbye'
  get '/site/categories'
  get '/site/products'

  resources :articles

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

	#Associations
	belongs_to :category
	has_many :cart_line_items
	has_many :order_products
	has_many :reviews

	validates_presence_of :category_id, :name, :base_price, :price, :stock
	validates_length_of :description, minimum: 4
	validates_numericality_of :base_price, :price, :stock

	mount_uploader :product_image, ProductImageUploader

	def get_category_name
		if(self.category_id.nil?)
			"N/A"
		else
			Category.find(self.category_id).name
		end
	end

	def is_sufficient_quantity_available(quantity)
		if(self.stock < quantity)
			return false
		else
			return true
		end
	end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	before_action :authenticate_user!, except: [:index, :show]
	before_action :check_is_admin, except: [:index, :show]
	
	def index
		if(!params[:sort])
			@products = Product.all
		elsif params[:sort] == "low-high"
			@products = Product.order('price')
		elsif params[:sort] == "high-low"
			@products = Product.order('price DESC')
		end

	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if(@product.save)
			redirect_to products_path, notice: "Succesfully created product #{@product.name}"
		else
			render action: "new"
		end
	end

	def show
		@product = Product.find(params[:id])

		@related_products = Product.where('category_id = ? AND price >= ? AND price <= ? AND id != ?',@product.category_id, @product.price - 100, @product.price + 100, @product.id).limit(5)
		#@product.category.products.where()

		@cart_line_item = CartLineItem.new
		@review = Review.new
		@reviews = @product.reviews.all
		
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if(@product.update_attributes(product_params))
			redirect_to product_path(@product), notice: "Successfully updated Product #{@product.name}"
		else
			render action: "edit"
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice: "Product #{@product.name} successfully deleted"
	end



	private

	def product_params
		params[:product].permit(:name, :description, :price, :base_price, :availability, :stock, :category_id, :product_image)
		# Protecting from mass assignment - which is a security feature.
	end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h2> Edit Product </h2>

<%= form_for @product do |f| %>

	<%= f.label :category %><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Catgeory" %><br/>

	<%= f.label :name %> <br/>
	<%= f.text_field :name %> <br/>

	<%= f.label :description %> <br/>
	<%= f.text_area :description, rows:5 %> <br/>

	<%= f.label :base_price %> <br/>
	<%= f.number_field :base_price %> <br/>

	<%= f.label :selling_price %> <br/>
	<%= f.number_field :price %> <br/>

	<%= f.label :availability %> <br/>
	<%= f.check_box :availability %> <br/>

	<%= f.label :stock %> <br/>
	<%= f.number_field :stock %> <br/>

	<%= f.submit %> or <%= link_to "Go Back", :back %>

<% end %>

app/views/products/index.html.erb
<H2> Listing Product( <%= @products.count%> ) </H2>

<%if user_signed_in? && current_user.is_admin %>
<%=link_to("Add products",new_product_path)%>| 
<% end %>
<%=link_to("products",products_path)%> | <%= link_to("high-low", products_path(sort: "high-low"))%> | <%= link_to("low-high", products_path(sort: "low-high"))%>


<!--
<H3> Total Products</H3>
<iframe src='http://localhost:4848/single/?appid=C%3A%5CUsers%5Cram%5CDocuments%5CQlik%5CSense%5CApps%5CRubyApp.qvf&obj=pdcJ&opt=nointeraction&select=clearall' style='border:none;'></iframe>
<iframe src='http://localhost:4848/single/?appid=C%3A%5CUsers%5Cram%5CDocuments%5CQlik%5CSense%5CApps%5CRubyApp.qvf&obj=tjPCtLf&select=clearall' style='border:none;'></iframe>
<br>
-->


	
	<ul>
		<% @products.each do |product| %>
			<li> <% if product.product_image_url.nil? %>
					<%= image_tag("/default.jpg", size: "20x20") %>
				<% else %>
					<%= image_tag(product.product_image_url, size: "20x20") %>
				<% end %>


			 <%= link_to product.name, product_path(product)%> - (INR <%=product.price%>) - (<%= product.category.try(:name)%>) -
			
			<%#= product.get_category_name : This uses a method that we created in the Class%> 
			<%#= product.category.name : This uses associations but if a foreign key is null it will throw an error for nil::NilClass, which can be handled using try%>
			<!--  #here we can call the method like we have done in the show page. Show page is the preferred way to do it -->
			
			</li>



		<%end%>

	</ul>
		
	

app/views/products/new.html.erb
<h2> Add Product </h2>

<%= form_for @product do |f| %>

	<%if @product.errors.any? %>
		<h3>These errors prohibited the form from being saved</h3>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<%end%>

		</ul>
	<%end%>


	<%= f.label :category %><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Catgeory" %><br/>
	<%= @product.errors.messages[:category_id].join(", ")%>

	<%= f.label :name %> <br/><%= @product.errors.messages[:category_id].join(", ")%>
	<%= f.text_field :name %> <br/>

	<%= f.label :description %> <br/>
	<%= f.text_area :description, rows:5 %> <br/>

	<%= f.label :base_price %> <br/>
	<%= f.number_field :base_price %> <br/>

	<%= f.label :selling_price %> <%= @product.errors.messages[:category_id].join(", ")%><br/>
	<%= f.number_field :price %> <br/>

	<%= f.label :availability %> <br/>
	<%= f.check_box :availability %> <br/>

	<%= f.label :stock %> <br/>
	<%= f.number_field :stock %> <br/>

	<%= f.label :product_image %><br/>
	<%= f.file_field :product_image %> <br/>

	<%= f.submit %>

<% end %>

app/views/products/show.html.erb
<H4> <%= @product.name %>  
 <small>
<%if user_signed_in? && current_user.is_admin %>
 
 	
 		<%= link_to"edit", edit_product_path(@product)%>
 		<%= link_to"destroy", product_path(@product), method: :delete, data: {confirm: "Are you sure"}%>

	 
 	
 
 <% end %>
</small>
 </H4> 

<% if @product.product_image_url.nil? %>
	<%= image_tag("/default.jpg", size: "150x150") %>

<% else %>
	<%= image_tag(@product.product_image_url, size: "150x150") %>
<% end %>


<h3>Category : <%= link_to @product.get_category_name, category_path(@product.category) %></h3>
<p> INR <%= @product.price %> </p>
<p> Stock : <%= @product.availability ? "is available : #{@product.stock} left" : "not available"%> </p>

<% if @product.availability%>
	<h4> Add to Cart </h4>

	<%= form_for @cart_line_item do |f| %>
		<label> Quantity : </label>
		<%= f.select :quantity, (1..5).to_a %>
		<%= f.hidden_field :product_id, value: @product.id %>
		<br/><br/>
		<%= f.submit "Add to Cart" %>
	<%end%>
<%else%>
	<p> Product currently not available<p>
<%end%>

<h2> Add Review </h2>

<%= form_for([@product,@review]) do |f|%>
<label> Rating </label>
<%= f.radio_button :rating, 1%> 1
<%= f.radio_button :rating, 2%> 2
<%= f.radio_button :rating, 3%> 3
<%= f.radio_button :rating, 4%> 4
<%= f.radio_button :rating, 5%> 5 <br/><br/>

<label> Title </label>
<%= f.text_field :title %> <br/>

<label> Body </label>
<%= f.text_area :body %> <br/>
<%= f.hidden_field :product_id, value: @product.id %> <br/>
<%= f.submit "Add Review" %>


<% end %>

<h2> Previous reviews </h2>
<%if @reviews.empty? %>
	<h2> No reviews for <%= @product.name %> yet </h2>	
<%else%>
	<% @reviews.each do |review| %>
		<table>
			<thead>
				<td> Review Title</td>
				<td> Review Rating</td>
				<td> User</td>
			</thead>
			<tbody>
				<td> <%= review.title %> </td>
				<td> <%= review.rating %> </td>
				<td> <%= review.user.username %> </td>
			</tbody>>
		</table>
	<%end%>
<%end%>


<p>Related Products</p>

<ul>
		<% @related_products.each do |related_product| %>
			<li> <%= link_to related_product.name, product_path(related_product)%> - (INR <%=related_product.price%>) - (<%= related_product.category.try(:name)%>)
			<%#= product.get_category_name : This uses a method that we created in the Class%> 
			<%#= product.category.name : This uses associations but if a foreign key is null it will throw an error for nil::NilClass, which can be handled using try%>
			<!--  #here we can call the method like we have done in the show page. Show page is the preferred way to do it -->
				

			</li>



		<%end%>

	</ul>


<%= link_to("Back",products_path)%>