config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'

  devise_for :users

  resources :products do
    resources :reviews
  end

  resources :categories

  resources :cart_line_items

  resources :orders

  get '/site/hello'
  get '/site/goodbye'
  get '/site/categories'
  get '/site/products'

  resources :articles

  root 'products#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	# When we have created an object in the controller and passing the cart directly to the model
	#This function returns three values : 
	#"updated_cart" : When a product exists in a cart and the same is added to the cart and the total quantity is below the limit
	#"max_cart" : When a product exists in a cart and the same is added to the cart but the limit of 5 has been reached
	#"added_cart" : When a product does not exist in the cart and a new line item is created
	def add_or_update
		success = ""

		user = self.user
		
		if user.cart_line_items.pluck(:product_id).include? self.product_id
			line_item = user.cart_line_items.find_by_product_id(self.product_id)
			if ((line_item.quantity + self.quantity)<=5)
				line_item.update_attributes(quantity: line_item.quantity + self.quantity)
				success = "updated_cart"
			else
				line_item.update_attributes(quantity: 5)
				success = "max_cart"
			end

		else
			self.save
			success = "added_cart"
		end
		return success
	end

	# When we have not created an object in the controller and passing the cart directly to the model
	# This is a class method for CartLineItem
	def self.add_or_update(cart_line_item)
		user = User.find(cart_line_item["user_id"])

		if user.cart_line_items.pluck(:product_id).include? cart_line_item[:product_id]

			line_item = user.cart_line_items.find_by_product_id(cart_line_item[:product_id])
			line_item.update_attributes(quantity: line_item.quantity + cart_line_item[:quantity])
		else 
			CartLineItem.create(cart_line_item)
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user
	has_many :order_products

	#Call Back

	before_save :generate_initial_order_details
	after_save :copy_cart_line_items_to_order_products
	after_save :delete_cart_line_items
	#after_save :send_order_confirmation_email

	def generate_initial_order_details
		self.order_number = "DCT - #{Random.rand(10..500)}"
		#self.order_date = Date.today
		self.total = calculate_order_total 
	end

	def copy_cart_line_items_to_order_products
		self.user.cart_line_items.each do |line_item|
			order_product = OrderProduct.new
			order_product.order_id = self.id
			order_product.product_id = line_item.product_id
			order_product.quantity = line_item.quantity
			order_product.price = line_item.product.price
			order_product.save
		end
	end

	def delete_cart_line_items
		CartLineItem.where('user_id = ?', self.user_id).delete_all
	end

	def send_order_confirmation_email
		Notification.order_confirmation(self).deliver
	end



	private

	def calculate_order_total
		total = 0
		self.user.cart_line_items.each do |line_item|
			total+= line_item.quantity * line_item.product.price
		end
		return total
	end



end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base

	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base

	#Associations
	belongs_to :category
	has_many :cart_line_items
	has_many :order_products
	has_many :reviews

	validates_presence_of :category_id, :name, :base_price, :price, :stock
	validates_length_of :description, minimum: 4
	validates_numericality_of :base_price, :price, :stock

	mount_uploader :product_image, ProductImageUploader

	def get_category_name
		if(self.category_id.nil?)
			"N/A"
		else
			Category.find(self.category_id).name
		end
	end

	def is_sufficient_quantity_available(quantity)
		if(self.stock < quantity)
			return false
		else
			return true
		end
	end


end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates_presence_of :title, :user_id, :product_id, :rating
	validates_numericality_of :rating
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cart_line_items
  has_many :orders
  has_many :reviews

  #after_create :send_welcome_message

  def send_welcome_message
  	Notification.welcome_user_message(self).deliver
  end

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	before_action :authenticate_user!

	def create
		@order = Order.new
		@order.user_id = current_user.id
		if @order.save
			#redirect_to root_path, notice: "Successfully created Order"
			redirect_to order_path(@order), notice: "Successfully added Order"
		end
	end

	def index
		@orders = current_user.orders
	end


	def show
		@order = Order.find(params[:id])
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :authenticate_user!

	def new
		@review = Review.new
		@product = Product.find(params[:product_id])
	end

	def create
		@review = Review.new(review_params)
		@review.user_id = current_user.id
		@product = Product.find(params[:product_id])
		if(@review.save)
			redirect_to product_path(@review.product), notice: "Thank You for adding a review"
		else
			render action: "new"	
		end



	end

	private

	def review_params
		params[:review].permit(:title, :body, :product_id, :rating)
	end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def hello
		@names = ["rajiv","poku"]
	end

	def goodbye
	end

	def categories
		@categories = Category.all
	end

	def products
		if(!params[:sort])
			@products = Product.all
		
		elsif (params[:sort] == "low-high")
			@products = Product.order('price')

		elsif(params[:sort] == "high-low")
			@products = Product.order('price DESC')
		end
			
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecomm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= link_to "Categories", categories_path %> | <%= link_to "Products", products_path %>

<br/>
<br/>


<% if user_signed_in? %>
	<% if current_user.is_admin %>
	<%= link_to "Dashboard", dashboard_index_path %>
<% end %>
	
 Howdy <%= current_user.username %> |<%= link_to "Your Orders", orders_path %>(<%= current_user.orders.size %>)| <%= link_to "Your Cart", cart_line_items_path %>(<%= current_user.cart_line_items.size %>)  | <%= link_to "Account Setting", edit_user_registration_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
 
  

 <%else%>
 	<%= link_to "Login", new_user_session_path %> | <%= link_to "Sign Up", new_user_registration_path %>

 <%end%>

<%= notice %>	
<%= alert %>
<%= yield %>

</body>
</html>

app/views/notification/order_confirmation.html.erb
<p> Hello <%= @order.user.username %>, </p>

<p> Your order has been confirmed. <br/>
Here are your order details
</p>


<ol>
	<% @order.order_products.each do |line_item| %>
	<li>
		<%= line_item.product.name %> - INR <%= line_item.price %> - <%= line_item.quantity %> units
	</li>
	<% end %>
</ol>

<strong> Total: <%= @order.total %> </strong> <br/>

<p> Thank you for shopping with us </p>

<%= image_tag("https://www.dctacademy.com/wp-content/uploads/2016/03/dct-final.jpg") %>

app/views/notification/order_confirmation.text.erb
Notification#order_confirmation

<%= @greeting %>, find me in app/views/notification/order_confirmation.text.erb

app/views/notification/welcome_user_message.html.erb
<p> Hello <%= @user.username %>, </p>

<p> Welcome to DCT Acad Ecomm Portal. <br/>
</p>



<p> Thanks for signing up with us </p>

<%= image_tag("https://www.dctacademy.com/wp-content/uploads/2016/03/dct-final.jpg") %>